#!/bin/sh
#
# Initialize tmux env for work
#
export MYTMUX=$(which tmux)
export SESSION=workon

if [ -z $MYTMUX ]; then
    echo "You need to install tmux."
    exit 1
fi

$MYTMUX has-session -t $SESSION

if [ $? != 0 ]; then
    $MYTMUX new-session -d -n workonw -s $SESSION
    $MYTMUX select-window -t $SESSION:1
fi

$MYTMUX attach -t $SESSION

exit 0
